name: IEEE_TSTE_2023
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - asciitree=0.3.3
  - async-timeout=4.0.2
  - attrdict=2.0.1
  - attrs=22.2.0
  - autograd=1.5
  - blinker=1.5
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - capytaine=1.4.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - cmocean=2.0
  - colorspacious=1.1.2
  - contourpy=1.0.7
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.3.0
  - dask-core=2023.3.0
  - dbus=1.13.18
  - decorator=5.1.1
  - distributed=2023.3.0
  - entrypoints=0.4
  - expat=2.5.0
  - fasteners=0.17.3
  - fontconfig=2.14.1
  - fonttools=4.39.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.3.0
  - future=0.18.3
  - gcsfs=2023.3.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.7.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.4.1
  - googleapis-common-protos=1.57.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - heapdict=1.0.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcrc32c=1.1.2
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - ncurses=6.3
  - nspr=4.35
  - nss=3.89
  - numba=0.56.4
  - numcodecs=0.11.0
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - packaging=23.0
  - partd=1.3.0
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.1.1
  - ply=3.11
  - pooch=1.7.0
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2023.02.02
  - readline=8.1.2
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.10.1
  - setuptools=67.6.0
  - sip=6.6.2
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.40.1
  - tblib=1.7.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wavespectra=3.13.0
  - wecopttool=2.1.0
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.2
  - zarr=2.13.6
  - zict=2.2.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - adal==1.2.7
    - azure-core==1.26.3
    - bottleneck==1.3.7
    - cachetools==4.2.4
    - cftime==1.6.2
    - fatpack==0.7.3
    - gmsh==4.11.1
    - google-api-core==2.10.2
    - google-api-python-client==2.81.0
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.5.3
    - h5py==3.8.0
    - h5pyd==0.10.3
    - httplib2==0.21.0
    - isodate==0.6.1
    - lxml==4.9.2
    - markdown-it-py==2.2.0
    - mdurl==0.1.2
    - meshio==5.3.4
    - mhkit==0.6.0
    - msrest==0.7.1
    - msrestazure==0.6.4
    - netcdf4==1.5.8
    - nrel-rex==0.2.79
    - pandas==1.5.0
    - patsy==0.5.3
    - pecos==0.2.0
    - pygments==2.14.0
    - pygmsh==7.1.17
    - pyqt5-sip==12.11.0
    - requests-unixsocket==0.3.0
    - rich==13.3.2
    - scikit-learn==1.2.2
    - statsmodels==0.13.5
    - threadpoolctl==3.1.0
    - uritemplate==4.1.1
    - xarray==2022.9.0
